### ISSUE TITLE
My head did not explode while reading your code.

### ISSUE THREAD

**Issue by Westcott1** [8none1/nspanel#1]
I was so looking forward to having to embrace the heat death of the universe as a welcome relief.
If that is how the universe does indeed end.
My project is very similar to yours: porting old ESP32+Nextion code to an NSpanel.
Complete with working OTA for both of them.
Your code showed me how to overcome all the undocumented initialisation challenges.
I used `attachInterrupt(key1, ISR1, CHANGE);` for reading keys, and some other random code to read the NTC.
THANKS AGAIN!

**Comment by 8none1** [comment]
Oh, nice idea on the `attachInterrupt` that's much tidier.  I'll move over to doing it that way too I think.

Glad that this helped you out somehow, thanks for the feedback!

**Comment by Westcott1** [comment]
Hi Will,

I discovered, after much Googling, that you can attach only one interrupt to any pin.

If you only want to know when it’s pressed, “FALLING” is fine.

For press and release I use “CHANGE” and a bool to keep track of direction.
